import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Node, Edge } from 'reactflow';
import { CustomNodeData } from '@/types';
import { FilterNodeData, ImageNodeData } from '@/types';

interface CreateCustomNodeDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedNodes: Node[];
  allNodes: Node[];  // All nodes on the canvas
  edges: Edge[];
  onCreateCustomNode: (customNode: Omit<CustomNodeData, 'id'>) => void;
}

export default function CreateCustomNodeDialog({
  open,
  onOpenChange,
  selectedNodes,
  allNodes,
  edges,
  onCreateCustomNode
}: CreateCustomNodeDialogProps) {
  const [name, setName] = useState('');
  const [category, setCategory] = useState('Custom');
  const [description, setDescription] = useState('');
  const [useAllActiveFilters, setUseAllActiveFilters] = useState(true);
  const [nodesToInclude, setNodesToInclude] = useState<Node[]>([]);
  
  // Effect to determine which nodes to include when dialog opens
  useEffect(() => {
    if (open) {
      if (useAllActiveFilters) {
        // Find all active filter nodes (excluding source/image nodes)
        const activeFilters = allNodes.filter(node => 
          node.type === 'filterNode' && 
          (node.data as FilterNodeData).enabled === true
        );
        setNodesToInclude(activeFilters);
      } else {
        // Use manually selected nodes
        setNodesToInclude(selectedNodes);
      }
    }
  }, [open, useAllActiveFilters, allNodes, selectedNodes]);
  
  // Filter only the edges that connect the included nodes
  const relevantEdges = edges.filter(edge => 
    nodesToInclude.some(node => node.id === edge.source) && 
    nodesToInclude.some(node => node.id === edge.target)
  );

  const handleCreateNode = () => {
    if (!name) return;
    
    // Check if we have nodes to include
    if (nodesToInclude.length === 0) {
      alert("Please enable at least one filter or select nodes manually");
      return;
    }
    
    // Create the custom node
    const customNode: Omit<CustomNodeData, 'id'> = {
      name,
      category,
      description,
      params: [], // Will be created during processing
      enabled: true,
      blendMode: 'normal',
      opacity: 1,
      internalNodes: nodesToInclude,
      internalEdges: relevantEdges,
      thumbnail: '' // Will be generated by the backend
    };
    
    onCreateCustomNode(customNode);
    onOpenChange(false);
    
    // Reset form
    setName('');
    setCategory('Custom');
    setDescription('');
    setUseAllActiveFilters(true);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Create Custom Node</DialogTitle>
          <DialogDescription>
            Create a reusable custom node from your selected nodes.
            {nodesToInclude.length === 0 ? (
              <p className="text-red-500 mt-2">No active filters found. Please enable at least one filter or select nodes manually.</p>
            ) : (
              <p className="mt-2">Using {nodesToInclude.length} filter node{nodesToInclude.length !== 1 ? 's' : ''}.</p>
            )}
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-6 py-4">
          <div className="space-y-2">
            <Label htmlFor="name">
              Name
            </Label>
            <Input
              id="name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="My Custom Filter"
              disabled={nodesToInclude.length === 0}
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="category">
              Category
            </Label>
            <Select
              value={category}
              onValueChange={setCategory}
              disabled={nodesToInclude.length === 0}
            >
              <SelectTrigger id="category">
                <SelectValue placeholder="Select a category" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Custom">Custom</SelectItem>
                <SelectItem value="Effects">Effects</SelectItem>
                <SelectItem value="Texture">Texture</SelectItem>
                <SelectItem value="Color">Color</SelectItem>
                <SelectItem value="Distortion">Distortion</SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="description">
              Description
            </Label>
            <Textarea
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="min-h-[80px]"
              placeholder="Describe what this custom node does"
              disabled={nodesToInclude.length === 0}
            />
          </div>
          
          <div className="flex items-center space-x-2">
            <Checkbox 
              id="useAllActiveFilters" 
              checked={useAllActiveFilters} 
              onCheckedChange={(checked) => setUseAllActiveFilters(checked as boolean)}
            />
            <Label htmlFor="useAllActiveFilters" className="text-sm font-normal cursor-pointer">
              Use all active filters on canvas (recommended)
            </Label>
          </div>
          
          <div className="col-span-4">
            <h4 className="text-sm font-medium mb-2">Included Nodes ({nodesToInclude.length})</h4>
            <ul className="text-sm text-gray-500 space-y-1 max-h-[100px] overflow-y-auto">
              {nodesToInclude.map(node => (
                <li key={node.id} className="truncate">
                  • {node.data.label || node.id}
                </li>
              ))}
              {nodesToInclude.length === 0 && (
                <li className="text-amber-600">No nodes selected. Please enable filters or select nodes manually.</li>
              )}
            </ul>
          </div>
        </div>
        
        <DialogFooter>
          <Button onClick={() => onOpenChange(false)} variant="outline">Cancel</Button>
          <Button 
            onClick={handleCreateNode} 
            disabled={!name || nodesToInclude.length === 0} 
            className="bg-amber-600 hover:bg-amber-700"
          >
            Create Custom Node
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}